import Head from 'next/head'
import Link from 'next/link'

export default function Layout({ title, children }) {
  return (
    <>
      <Head>
        <title> {title ? title + ' - NextShop' : 'NextShop'} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex flex-row h-12 items-center px-4 justify-between shadow-md bg-slate-200">
            <Link href="/" className="text-lg font-bold">
              NextShop
            </Link>
            <div>
              <Link href="/info" className="p-4">
                Info
              </Link>
            </div>
            <div>
              <Link href="/cart" className="p-4">
                Cart
              </Link>
              <Link href="/login" className="p-4">
                Login
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex h-10 justify-center items-center shadow-inner bg-red-300">
          <p>Copyright &copy; 2022 NextShop, Byoungcheon Lee </p>
        </footer>
      </div>
    </>
  )
}
