import Head from 'next/head'
import Link from 'next/link'
import { useContext } from 'react'
import { Store } from '../utils/Store'

export default function Layout({ title, children }) {
  const { state } = useContext(Store)
  const { cart } = state

  return (
    <>
      <Head>
        <title> {title ? title + ' - NextShop' : 'NextShop'} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex flex-row h-12 items-center px-4 justify-between shadow-md bg-slate-200">
            <Link href="/" className="text-lg font-bold">
              NextShop
            </Link>
            <div>
              <Link href="/fortpolio" className="p-4">
                Fortfolio
              </Link>
              <Link href="/crypto" className="p-4">
                Crypto
              </Link>
            </div>
            <div>
              <Link href="/cart" className="p-4">
                Cart
                {cart.cartItems.length > 0 && (
                  <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                    {cart.cartItems.reduce((a, c) => a + c.quantity, 0)}
                  </span>
                )}
              </Link>
              <Link href="/login" className="p-4">
                Login
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex h-10 justify-center items-center shadow-inner bg-red-300">
          <p>Copyright &copy; 2022 NextShop, Byoungcheon Lee </p>
        </footer>
      </div>
    </>
  )
}
